spring:
   mvc:
    locale: pt_BR
  jackson:
     locale: pt_BR
     date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
     write-dates-as-timestamps: false
     serialization-inclusion: non_null
     indent_output: true
     deserialization:
        READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
