server:
  port: 9000
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
feign:
  client:
    config:
      feignName:
        errorDecoder: com.usecases.spring.gateway.config.ErrorDecoderImpl