server:
  port: 8082
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Person?serverTimezone=America/Sao_Paulo&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    jmx-enabled: false
    max-active: 10
    initialSize: 2
    max-idle: 15
    min-idle: 15
    max-wait: 10000
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 20000
    validationQuery: select 1
